### ISSUE TITLE
Should this be called 'schemas'?

### ISSUE THREAD

**Issue by MattElcock** [ONSdigital/eq-questionnaire-registry#17]
https://github.com/ONSdigital/eq-questionnaire-registry/blob/58efb12ad8121f3e4b7011b7b0d3250a1ee1ad6e/middleware/insertIntoRegistry.test.js#L16

I was meant to speak to you about this the other day, but forgot, should this be called 'schemas'? We're using 'schema' elsewhere to name the Runner JSON, so I think this might confuse things as we're giving the same name two meanings here. I'd suggest renaming this to be 'variants', or something similar, as the contents defines different variations of the survey/questionnaire.

**Comment by martyncolmer** [comment]
I half agree with you here, although in future if we are tieing in different languages in a more complicated publish process then there would be other schemas. Which I suppose could be a variant.

**Comment by martyncolmer** [comment]
Changed to variants
