### ISSUE TITLE
Why are there two versions of this file?

### ISSUE THREAD

**Issue by MattElcock** [ONSdigital/eq-questionnaire-registry#18]
https://github.com/ONSdigital/eq-questionnaire-registry/blob/58efb12ad8121f3e4b7011b7b0d3250a1ee1ad6e/middleware/insertQuestionnaireIntoRegistry.js#L1

You have made an `insertIntoRegistry` file and `insertQuestionnaireIntoRegistry` file, why?

**Comment by martyncolmer** [comment]
One is for pulling from publisher, one is for submitting json

**Comment by MattElcock** [comment]
Ahh right OK, that's fine then. I remember you telling me about that now.
