### ISSUE TITLE
Consider destructing params instead of repeatedly referencing

### ISSUE THREAD

**Issue by MattElcock** [ONSdigital/eq-questionnaire-registry#3]
https://github.com/ONSdigital/eq-questionnaire-registry/blob/30a59b58962694cb49f2897de106fa4488f27d17/database/firestore.js#L18

You could destructure the `params` object into variables and then use them throughout the code, rather than repeatedly going to `params.VARIABLE` to get them, e.g. `const {id, form_type, survey_id} = params`. It'll make the code slightly more readable, then. 

For reference if you've not come across object and array destructuring in JS before: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment

**Comment by martyncolmer** [comment]
Done
