### ISSUE TITLE
Do we need this console.log()? If so, change to console.error()

### ISSUE THREAD

**Issue by MattElcock** [ONSdigital/eq-questionnaire-registry#4]
https://github.com/ONSdigital/eq-questionnaire-registry/blob/30a59b58962694cb49f2897de106fa4488f27d17/database/firestore.js#L20

If you're throwing an error beneath this, do we need the `console.log()`? If so, perhaps consider changing it to `console.error()`.

**Comment by martyncolmer** [comment]
Done
