### ISSUE TITLE
Perhaps should not be modifying function parameters directly

### ISSUE THREAD

**Issue by MattElcock** [ONSdigital/eq-questionnaire-registry#6]
https://github.com/ONSdigital/eq-questionnaire-registry/blob/30a59b58962694cb49f2897de106fa4488f27d17/database/firestore.js#L35

I don't feel like we should be modifying the function parameters directly; if you decide to employ the object destructuring, you could use it to get and store the version and modify the resulting variable instead.

**Comment by martyncolmer** [comment]
Done
