### ISSUE TITLE
Do we need this console.log()? If so, change to console.error()

### ISSUE THREAD

**Issue by MattElcock** [ONSdigital/eq-questionnaire-registry#7]
https://github.com/ONSdigital/eq-questionnaire-registry/blob/30a59b58962694cb49f2897de106fa4488f27d17/database/firestore.js#L56 

Similar to #4 - do we need this `console.log()` if we are throwing an error beneath? If so, consider changing to `console.error()` .

**Comment by martyncolmer** [comment]
updated
