### ISSUE TITLE
Consider destructuring the data object

### ISSUE THREAD

**Issue by MattElcock** [ONSdigital/eq-questionnaire-registry#8]
https://github.com/ONSdigital/eq-questionnaire-registry/blob/30a59b58962694cb49f2897de106fa4488f27d17/database/firestore.js#L64

Similar to #3 - less important 'though as we're only using these values once within the function, which is quite small. However, it could improve readability if we destructure the `data` object.

**Comment by martyncolmer** [comment]
Done
